name: apollo_flutter
description: A running timer app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  wakelock: ^0.6.1+2

dev_dependencies:
  dart_code_metrics: ^4.15.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
